import { Complaint } from "./types";

export const CATEGORY_LABELS: Record<string, string> = {
  safety: "Safety & Security",
  electrical: "Electrical",
  plumbing: "Plumbing",
  wifi: "WiFi & Network",
  cleanliness: "Cleanliness",
  other: "Other",
};

export const CATEGORY_COLORS: Record<string, string> = {
  safety: "bg-red-100 text-red-700 border-red-200",
  electrical: "bg-orange-100 text-orange-700 border-orange-200",
  plumbing: "bg-blue-100 text-blue-700 border-blue-200",
  wifi: "bg-purple-100 text-purple-700 border-purple-200",
  cleanliness: "bg-green-100 text-green-700 border-green-200",
  other: "bg-slate-100 text-slate-700 border-slate-200",
};

// Registered Student Mocks for Realistic Block Filtering
export const MOCK_COMPLAINTS: Complaint[] = [
  // Kitchen Electrical Cluster (Bhaskara Block)
  {
    id: "C-001",
    studentName: "Amit Patel",
    studentId: "STU103",
    roomNumber: "102",
    hostelBlock: "Bhaskara-Main",
    category: "electrical",
    description: "Electrical problem in kitchen area",
    location: "Kitchen",
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    status: "open",
    priorityScore: 0.6,
    explanation: "Detected electrical hazard in common area.",
    mlComponents: {
      severity: 0.6,
      frequency: 0.1,
      urgency: 0.4,
      timeFactor: 0.1,
      impactMultiplier: 1.0,
      frustration: 0.5,
      emotion: "neutral",
    },
    affectedCount: 1,
  },
  {
    id: "C-002",
    studentName: "Amit Patel",
    studentId: "STU103",
    roomNumber: "102",
    hostelBlock: "Bhaskara-Main",
    category: "electrical",
    description: "Kitchen shock risk - exposed wires near fridge.",
    location: "Kitchen",
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    status: "open",
    priorityScore: 0.78,
    explanation: "🔥 CLUSTER ALERT: Repeating electrical hazards in Kitchen.",
    mlComponents: {
      severity: 0.8,
      frequency: 0.6,
      urgency: 0.6,
      timeFactor: 0.1,
      impactMultiplier: 1.0,
      frustration: 0.5,
      emotion: "neutral",
    },
    affectedCount: 1,
  },
  // WiFi Cluster (Aryabhatta Block)
  {
    id: "C-003",
    studentName: "Priya Singh",
    studentId: "STU102",
    roomNumber: "305",
    hostelBlock: "Aryabhatta-A",
    category: "wifi",
    description: "Internet down in 305 - unable to open LMS.",
    location: "Room 305",
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    status: "open",
    priorityScore: 0.45,
    explanation: "Localised WiFi outage in room.",
    mlComponents: {
      severity: 0.3,
      frequency: 0.1,
      urgency: 0.3,
      timeFactor: 0.3,
      impactMultiplier: 1.0,
      frustration: 0.5,
      emotion: "neutral",
    },
    affectedCount: 1,
  },
  {
    id: "C-004",
    studentName: "Rahul Sharma",
    studentId: "STU101",
    roomNumber: "302",
    hostelBlock: "Aryabhatta-A",
    category: "plumbing",
    description: "Water leaking near washroom pipe.",
    location: "Floor 2 Washroom",
    createdAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    status: "open",
    priorityScore: 0.55,
    explanation: "Plumbing issue flagged in common facility.",
    mlComponents: {
      severity: 0.5,
      frequency: 0.1,
      urgency: 0.4,
      timeFactor: 0.1,
      impactMultiplier: 1.0,
      frustration: 0.5,
      emotion: "neutral",
    },
    affectedCount: 5,
  },
];
